/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_intocps_java_fmi_shm_SharedMemory */

#ifndef _Included_org_intocps_java_fmi_shm_SharedMemory
#define _Included_org_intocps_java_fmi_shm_SharedMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_intocps_java_fmi_shm_SharedMemory
 * Method:    setId
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_intocps_java_fmi_shm_SharedMemory_setId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_intocps_java_fmi_shm_SharedMemory
 * Method:    read
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_intocps_java_fmi_shm_SharedMemory_read
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_intocps_java_fmi_shm_SharedMemory
 * Method:    send
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_org_intocps_java_fmi_shm_SharedMemory_send
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     org_intocps_java_fmi_shm_SharedMemory
 * Method:    setDebug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_intocps_java_fmi_shm_SharedMemory_setDebug
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_intocps_java_fmi_shm_SharedMemory
 * Method:    waitForWatchDogEvent
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_org_intocps_java_fmi_shm_SharedMemory_waitForWatchDogEvent
  (JNIEnv *, jobject);

/*
 * Class:     org_intocps_java_fmi_shm_SharedMemory
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_intocps_java_fmi_shm_SharedMemory_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
