/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_intocps_java_fmi_shm_SharedMemoryServer */

#ifndef _Included_org_intocps_java_fmi_shm_SharedMemoryServer
#define _Included_org_intocps_java_fmi_shm_SharedMemoryServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_intocps_java_fmi_shm_SharedMemoryServer
 * Method:    serverStart
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_intocps_java_fmi_shm_SharedMemoryServer_serverStart
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_intocps_java_fmi_shm_SharedMemoryServer
 * Method:    setServerDebug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_intocps_java_fmi_shm_SharedMemoryServer_setServerDebug
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_intocps_java_fmi_shm_SharedMemoryServer
 * Method:    serverSend
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_org_intocps_java_fmi_shm_SharedMemoryServer_serverSend
  (JNIEnv *, jobject, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
