/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_intocps_java_fmi_shm_SharedMemory_NativeFmuApi */

#ifndef _Included_org_intocps_java_fmi_shm_SharedMemory_NativeFmuApi
#define _Included_org_intocps_java_fmi_shm_SharedMemory_NativeFmuApi
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
