name: Build with c++ for windows

on: [push, pull_request]


jobs:

  compileWindowsx64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: "Build windows x64"
        run: ./scripts/compile-win64.sh

      - uses: actions/upload-artifact@v2
        with:
          name: win-x64
          path: builds/winx64/shmfmi-server/sharedmemory.dll

      - uses: actions/upload-artifact@v2
        with:
          name: win-x64
          path: builds/winx64/libshmfmu/libshmfmu.dll

  compileWindowsx32:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: "Build windows x86"
        run: ./scripts/compile-win32.sh

      - uses: actions/upload-artifact@v2
        with:
          name: win-x32
          path: builds/winx32/shmfmi-server/sharedmemory.dll

      - uses: actions/upload-artifact@v2
        with:
          name: win-x32
          path: builds/winx32/libshmfmu/libshmfmu.dll

  compileLinuxx32:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: "Build linux x32"
        run: ./scripts/compile-linux32.sh

      - uses: actions/upload-artifact@v2
        with:
          name: linux-x32
          path: builds/linux-x32/shmfmi-server/libsharedmemory.so

      - uses: actions/upload-artifact@v2
        with:
          name: linux-x32
          path: builds/linux-x32/libshmfmu/liblibshmfmu.so

#  compileLinuxx64:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          submodules: 'true'
#      - name: "Build linux x64"
#        run: ./scripts/compile-linux64.sh
#      - uses: actions/upload-artifact@v2
#        with:
#          name: linux-x64
#          path: builds/linux-x64/shmfmi-server/libsharedmemory.so
#
#      - uses: actions/upload-artifact@v2
#        with:
#          name: linux-x64
#          path: builds/linux-x64/libshmfmu/liblibshmfmu.so

#  compileMacOSXx64:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          submodules: 'true'
#      - name: "Build MacOSX x64"
#        run: ./scripts/compile-mac.sh
#      - uses: actions/upload-artifact@v2
#        with:
#          name: macos-x64
#          path: builds/mac/shmfmi-server/libsharedmemory.dylib
#
#      - uses: actions/upload-artifact@v2
#        with:
#          name: macos-x64
#          path: builds/mac/libshmfmu/liblibshmfmu.dylib