name: Build with c++ on windows

on: [push, pull_request]


jobs:

  compileWindows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: "Build windows x64"
        run: ./scripts/compile-win64.sh

      - name: "Build windows x86"
        run: ./scripts/compile-win64.sh